apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-rolebinding
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: default  # Change to the namespace where Spark runs
roleRef:
  kind: ClusterRole
  name: spark-role
  apiGroup: rbac.authorization.k8s.io