apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["*"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]

  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["*"]